### ISSUE TITLE
.NET SDK not Listing .NET 5 and 6

### ISSUE THREAD

**Issue by seikosantana** [consulo/consulo-dotnet-core#9]
Hi, thank you for the effort on the IDE.

![image](https://user-images.githubusercontent.com/35630407/155065207-f421261a-53c8-4c7e-bc51-67ed0e3a0c3b.png)
As the title said, SDKs are detected in settings but when creating new projects, there's no option to create .NET (5 and 6). Did I miss any configurations? Thanks in advance.

**Comment by m1ntkat** [comment]
Hey, I'm encountering the same problem
![Screenshot_2023-04-04_21-03-56](https://user-images.githubusercontent.com/85989407/229985915-44912adc-2a27-492b-93f5-7a68f141f2d7.png)
![Screenshot_2023-04-04_21-04-40](https://user-images.githubusercontent.com/85989407/229985924-d7f2c989-5a95-4d64-ab32-7c39738b6a25.png)

**Comment by VISTALL** [comment]
Hello. Looks like your problem was fixed in this PR https://github.com/consulo/incubating-consulo-dotnet-core/pull/10, but this PR will affect only new builds of Consulo, current stable builds - not update for now (since current nightly builds not stable)

Can you say what .NET you using? 

Problem in file `dotnet\sdk\7.0.102\.version` which was changed:

```
4bbdd14480a177e60fba52abf34829020449e46e
7.0.102
win-x64
7.0.102-servicing.22607.3
```

For now plugin allow extracting version only with 3 line file (not four). And test it.

**Comment by m1ntkat** [comment]
`6.0.113`

**Comment by m1ntkat** [comment]
I fixed the issue by adding the sdk manualy
